### ISSUE TITLE
High Idle usage

### ISSUE THREAD

**Issue by erikjoya** [JamesCJ60/AMD-APU-Tuning-Utility#58]
When running uxtu in the background. It's consuming around 2-5% of cpu usage. Not really friendly with laptop battery.  
from idle 7w to easy 16w.

**Comment by JamesCJ60** [comment]
Should be fixed as of the latest release.

**Comment by erikjoya** [comment]
Not fixed under 1.03Loading uxtu app itself will cost my laptop to use 5% cpu even on idle. The cpu usage is showing under system on windows 11 task manager. Exiting the app will make the system cpu usage go down to 0. Lenovo Slim 7 Pro X, latest windows 11  Sent from Mail for Windows From: James Craddock-JonesSent: Friday, February 3, 2023 9:32 AMTo: JamesCJ60/AMD-APU-Tuning-UtilityCc: erikjoya; AuthorSubject: Re: [JamesCJ60/AMD-APU-Tuning-Utility] High Idle usage (Issue #58) Should be fixed as of the latest release.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by erikjoya** [comment]
Not fixed under 1.03Loading uxtu app itself will cost my laptop to use 5% cpu even on idle. The cpu usage is showing under system on windows 11 task manager. Exiting the app will make the system cpu usage go down to 0. Lenovo Slim 7 Pro X, latest windows 11   Sent from Mail for Windows From: James Craddock-JonesSent: Friday, February 3, 2023 9:32 AMTo: JamesCJ60/AMD-APU-Tuning-UtilityCc: erikjoya; AuthorSubject: Re: [JamesCJ60/AMD-APU-Tuning-Utility] High Idle usage (Issue #58) Should be fixed as of the latest release.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
